services:
  backend:
    build: ./
    container_name: backend
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      MESSAGE_TIMEOUT: ${MESSAGE_TIMEOUT}
      LOG_FILE_PATH: ${LOG_FILE_PATH}
    networks:
      - backend
    volumes:
      - log-data:/subscriber_bot/${LOG_FILE_PATH}
    depends_on:
      - db
  db:
    image: redis
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
    volumes:
      - db-data:/data
    ports:
      - 6380:6379
volumes:
  db-data:
  log-data:
networks:
  backend:
